# Permalinks
permalink:      /:year/:month/:day/:title

# Setup
title:          RunnerLee
paginate:       10
baseurl:        ""
url:            "https://runnerlee.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         RunnerLee
  url:          https://github.com/RunnerLee
  email:        runnerleer@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/RunnerLee/runnerlee.github.io

# Gems
gems:
  - jekyll-paginate

ga:
  id: UA-104881530-1
  url: runnerlee.com
